/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproj;

import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
//import sql_table.Stores;
//import sql_table.Floor;


/**
 *
 * @author MTC
 */
public class Add_Tenantstore1 extends javax.swing.JFrame {

    /**
     * Creates new form Add_store
     */
    public Add_Tenantstore1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("GUIprojPU").createEntityManager();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addd = new javax.swing.JButton();
        canclee = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        button1.setLabel("button1");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ashraf Hamayel\\Desktop\\adddd.jpg")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ashraf Hamayel\\Desktop\\ewewwe.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(150, 50, 192, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("TENANT ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 40, 140, 33);

        addd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addd.setText("Add");
        addd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddActionPerformed(evt);
            }
        });
        getContentPane().add(addd);
        addd.setBounds(340, 210, 180, 40);

        canclee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canclee.setText("Cancel");
        canclee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleeActionPerformed(evt);
            }
        });
        getContentPane().add(canclee);
        canclee.setBounds(740, 310, 90, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("     @Add TENANT information");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 0, 230, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ID STORE:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 80, 120, 33);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("CONTRACT END DATE:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 80, 170, 33);

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(150, 90, 192, 20);

        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        getContentPane().add(t9);
        t9.setBounds(590, 80, 192, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("STORE TYPE :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 120, 110, 33);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("CONTRACT START DATE:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(380, 40, 190, 33);

        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        getContentPane().add(t7);
        t7.setBounds(150, 130, 192, 20);

        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        getContentPane().add(t8);
        t8.setBounds(590, 50, 192, 20);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/wq.jpg"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(-500, -230, 1380, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    
    
    private void adddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddActionPerformed
        
         
        
       
          EntityManager em1= Persistence.createEntityManagerFactory("GUIprojPU").createEntityManager();
              em1.getTransaction().begin();
            
             
         
           int tid=Integer.parseInt(this.t2.getText());
          
           int tidstore=Integer.parseInt(this.t4.getText());
           String storetype=t7.getText();
            String tsdate=t8.getText();
             String tedate=t9.getText();
             
          TenantOwner tnt1 = new TenantOwner();
           TenantOwner tnt2 = new TenantOwner();
          Stores f=new Stores();
          
          
           Query qr1=em1.createNamedQuery("TenantOwner.findAll");
      List<TenantOwner> allTenant=qr1.getResultList();
          
          Query qr2=em1.createNamedQuery("Stores.findAll");
          List<Stores> allStores=qr2.getResultList();
          
           boolean t =false;
          
          
          for(TenantOwner ss:allTenant)
          {
          
          if(ss.getTenantOwnerId()==tid)
                  {
               tnt1=ss;
            t =true;
            }
         
         }
         
          if(!t)
          {
                     JOptionPane.showMessageDialog(null, " Id Tenant Does not exist  , \n Go to the option to add a new  tenant  ");
           
          
          
          }
      else
          {
            t =false;
        
          for (Stores ff:allStores)
          {
              
         if(ff.getIdStore()==tidstore)
          t =true;
         
          }
          
           if(!t)
          {
           JOptionPane.showMessageDialog(null, " Id Store Does not exist ");
           
           //this.setVisible(false);
          
          }
            
           
           
           
           
           
      else
          {
              
              t =false;
              for(TenantOwner ss:allTenant)
                  
          {
          
          if(ss.getIdStore()==tidstore)
                    t =true;
          }
          if(t)
          {
           JOptionPane.showMessageDialog(null, " This shop is already rented");
           
           //this.setVisible(false);
          
          }
          else 
          {
              
             
            
            
                  tnt2.setTenantOwnerName( tnt1.getTenantOwnerName());

                    tnt2.setTenantOwnerId(tid);

                    tnt2.setTenantOwnerPhone(tnt1.getTenantOwnerPhone());

            
                    
                    tnt2.setIdStore(tidstore);

                    tnt2.setAddress( tnt1.getAddress());

                    tnt2.setSex(tnt1.getSex());

                    tnt2.setStoreType( storetype);

                    tnt2.setContractStartDate( tsdate);

                    tnt2.setContractEndDate( tedate);

         
         em1.persist(tnt2);
         
         em1.getTransaction().commit();
         em1.close();
         
          JOptionPane.showMessageDialog(null, "Added");
          this.setVisible(false);
         
         
          }
          }//end else
        
    
          } 
        
    }//GEN-LAST:event_adddActionPerformed

    private void cancleeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleeActionPerformed
      
  
        this.setVisible(false);
       
        
        
    }//GEN-LAST:event_cancleeActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Tenantstore1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Tenantstore1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Tenantstore1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Tenantstore1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Add_Tenantstore1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addd;
    private java.awt.Button button1;
    private javax.swing.JButton canclee;
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
