/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproj;

import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
//import sql_table.Stores;
//import sql_table.Floor;


/**
 *
 * @author MTC
 */
public class Add_EMPLOYEE1 extends javax.swing.JFrame {

    /**
     * Creates new form Add_store
     */
    public Add_EMPLOYEE1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("GUIprojPU").createEntityManager();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        e2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        e1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        e5 = new javax.swing.JTextField();
        e3 = new javax.swing.JTextField();
        addd = new javax.swing.JButton();
        canclee = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        e4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        e6 = new javax.swing.JTextField();
        e7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        button1.setLabel("button1");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ashraf Hamayel\\Desktop\\adddd.jpg")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ashraf Hamayel\\Desktop\\ewewwe.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        getContentPane().add(e2);
        e2.setBounds(640, 60, 192, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("EMPLOYEE ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 50, 140, 33);

        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        getContentPane().add(e1);
        e1.setBounds(170, 60, 192, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("EMPLOYEE  NAME :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 50, 170, 33);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("SEX :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(480, 140, 130, 33);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("EMPLOYEE PHONE:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 100, 136, 27);

        e5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e5ActionPerformed(evt);
            }
        });
        getContentPane().add(e5);
        e5.setBounds(640, 150, 192, 20);

        e3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3ActionPerformed(evt);
            }
        });
        getContentPane().add(e3);
        e3.setBounds(170, 100, 192, 20);

        addd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addd.setForeground(new java.awt.Color(0, 0, 153));
        addd.setText("Add");
        addd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddActionPerformed(evt);
            }
        });
        getContentPane().add(addd);
        addd.setBounds(390, 260, 180, 40);

        canclee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canclee.setText("Cancel");
        canclee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleeActionPerformed(evt);
            }
        });
        getContentPane().add(canclee);
        canclee.setBounds(780, 290, 90, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("     @Add EMPLOYEE information");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 320, 230, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("EMPLOYEE  SALARY :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 90, 160, 33);

        e4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e4ActionPerformed(evt);
            }
        });
        getContentPane().add(e4);
        e4.setBounds(640, 100, 192, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("ADDRESS :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 140, 150, 33);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("FLOOR  NUMBER :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(220, 200, 140, 33);

        e6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e6ActionPerformed(evt);
            }
        });
        getContentPane().add(e6);
        e6.setBounds(170, 150, 192, 20);

        e7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e7ActionPerformed(evt);
            }
        });
        getContentPane().add(e7);
        e7.setBounds(360, 200, 192, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/GettyImages-1215953761.jpg"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, -10, 460, 360);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/new-employee4.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(460, 0, 420, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e2ActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e1ActionPerformed

    private void e5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e5ActionPerformed

    private void e3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e3ActionPerformed

    
    
    private void adddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddActionPerformed
        
         
        
       
          EntityManager em1= Persistence.createEntityManagerFactory("GUIprojPU").createEntityManager();
              em1.getTransaction().begin();
            
             
          String EMPLOYEE_NAME=e1.getText();
           int EMPLOYEE_ID=Integer.parseInt(this.e2.getText());
          long EMPLOYEE_PHONE=Integer.parseInt(this.e3.getText());
           int EMPLOYEE_SALARY=Integer.parseInt(this.e4.getText());
           String EMPLOYEE_SEX=e5.getText();
             String EMPLOYEE_ADDRESS=e6.getText();
          int FLOOR_NUMBER=Integer.parseInt(this.e7.getText());
           
          
           
             
          Employee Emplo = new Employee();
          Floor f=new Floor();
          
          
           Query qr1=em1.createNamedQuery("Employee.findAll");
      List<Employee> allEmployee=qr1.getResultList();
          
          Query qr2=em1.createNamedQuery("Floor.findAll");
          List<Floor> allFloor=qr2.getResultList();
          
           boolean t =false;
          
          
          for(Employee ss:allEmployee)
          {
          
          if(ss.getEmployeeId()==EMPLOYEE_ID)
                    t =true;
         
         }
         
          if(t)
          {
                     JOptionPane.showMessageDialog(null, " Id Employee Already exists  ");

           
          
          
          }
      else
          {
            t =false;
        
          for (Floor ff:allFloor)
          {
              
         if(ff.getFloorId()==FLOOR_NUMBER)
          t =true;
         
          }
          
           if(!t)
          {
           JOptionPane.showMessageDialog(null, " FLOOR NUMBER Does not exist ");
           
         
          
          }
            
           
           
           
           
           
      else
          {
              
        Emplo.setEmployeeName(EMPLOYEE_NAME);
     Emplo.setEmployeeId(EMPLOYEE_ID);
              Emplo.setEmployeePhone(EMPLOYEE_PHONE);
            Emplo.setEmployeeSalary(EMPLOYEE_SALARY);
             Emplo.setEmployeeSex(EMPLOYEE_SEX);
             Emplo.setEmployeeAddress(EMPLOYEE_ADDRESS);
           f.setFloorId(FLOOR_NUMBER);
           Emplo.setFloorNumber(f);
      
                        
   
         em1.persist(Emplo);
         
         em1.getTransaction().commit();
         em1.close();
         
          JOptionPane.showMessageDialog(null, "Added");
          this.setVisible(false);
         
         
          }
          }//end else
        
    
          
        
    }//GEN-LAST:event_adddActionPerformed

    private void cancleeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleeActionPerformed
      
  
        this.setVisible(false);
       
        
        
    }//GEN-LAST:event_cancleeActionPerformed

    private void e4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e4ActionPerformed

    private void e6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e6ActionPerformed

    private void e7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_EMPLOYEE1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_EMPLOYEE1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_EMPLOYEE1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_EMPLOYEE1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Add_EMPLOYEE1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addd;
    private java.awt.Button button1;
    private javax.swing.JButton canclee;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e3;
    private javax.swing.JTextField e4;
    private javax.swing.JTextField e5;
    private javax.swing.JTextField e6;
    private javax.swing.JTextField e7;
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
