/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproj;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
//import sql_table.Stores;
//import sql_table.Floor;


/**
 *
 * @author MTC
 */
public class Add_store extends javax.swing.JFrame {

    /**
     * Creates new form Add_store
     */
    public Add_store() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        floorstore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idstore = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        storeowner = new javax.swing.JTextField();
        storeyear = new javax.swing.JTextField();
        addd = new javax.swing.JButton();
        canclee = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        floorstore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorstoreActionPerformed(evt);
            }
        });
        getContentPane().add(floorstore);
        floorstore.setBounds(201, 103, 192, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("store Floor:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 109, 90, 33);

        idstore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idstoreActionPerformed(evt);
            }
        });
        getContentPane().add(idstore);
        idstore.setBounds(201, 65, 192, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("store id:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(12, 58, 88, 33);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("STORE PRICE TO OWNER:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 197, 185, 33);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("STORE PRICE PER YEAR:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 153, 176, 27);

        storeowner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeownerActionPerformed(evt);
            }
        });
        getContentPane().add(storeowner);
        storeowner.setBounds(201, 205, 192, 20);

        storeyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeyearActionPerformed(evt);
            }
        });
        getContentPane().add(storeyear);
        storeyear.setBounds(201, 158, 192, 20);

        addd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addd.setText("Add");
        addd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddActionPerformed(evt);
            }
        });
        getContentPane().add(addd);
        addd.setBounds(122, 236, 171, 31);

        canclee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canclee.setText("Cancel");
        canclee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleeActionPerformed(evt);
            }
        });
        getContentPane().add(canclee);
        canclee.setBounds(310, 270, 80, 31);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("     Add store information");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(201, 0, 192, 28);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/unnamed.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void floorstoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorstoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorstoreActionPerformed

    private void idstoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idstoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idstoreActionPerformed

    private void storeownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeownerActionPerformed

    private void storeyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeyearActionPerformed

    private void adddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddActionPerformed
         EntityManager em1= Persistence.createEntityManagerFactory("GUIprojPU").createEntityManager();
         
           
          int IdStore=Integer.parseInt(this.idstore.getText());
           int floorStore=Integer.parseInt(this.floorstore.getText());
          int yearStore=Integer.parseInt(this.storeyear.getText());
           int ownerStore=Integer.parseInt(this.storeowner.getText());
           
          Floor f = new Floor();
          
          
          
           Query qr1=em1.createNamedQuery("Stores.findAll");
      List<Stores> allstore=qr1.getResultList();
          
          Query qr2=em1.createNamedQuery("Floor.findAll");
          List<Floor> allfloor=qr2.getResultList();
          
           boolean t =false;
          Stores store=new Stores();
          
          for(Stores ss:allstore)
          {
          
          if(ss.getIdStore()==IdStore)
          t =true;
         
         }
         
          if(t)
          {
           JOptionPane.showMessageDialog(null, " Id Store Already exists ");
           
           //this.setVisible(false);
          
          }
      else
          {
      
        
          for (Floor ff:allfloor)
          {
              
         if(ff.getFloorId()==floorStore)
          t =true;
         
          }
          
           if(!t)
          {
           JOptionPane.showMessageDialog(null, " Id Floor Does not exist ");
           
           //this.setVisible(false);
          
          }
      else
          {
         
        store.setIdStore(IdStore);
         f.setFloorId(floorStore);
        store.setStoreFloor(f);
        store.setStorePricePerYear(yearStore);
        store.setStorePriceToOwn(ownerStore);
         em1.getTransaction().begin();
         em1.persist(store);
         em1.getTransaction().commit();
         em1.close();
         
          JOptionPane.showMessageDialog(null, "Added");
          this.setVisible(false);
          }
          }//end else
        
         
       // JOptionPane.showMessageDialog(null, " true ");
       // this.setVisible(false);
        
           
           
        
    }//GEN-LAST:event_adddActionPerformed

    private void cancleeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleeActionPerformed
      
  
        this.setVisible(false);
       
        
        
    }//GEN-LAST:event_cancleeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Add_store().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addd;
    private javax.swing.JButton canclee;
    private javax.swing.JTextField floorstore;
    private javax.swing.JTextField idstore;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField storeowner;
    private javax.swing.JTextField storeyear;
    // End of variables declaration//GEN-END:variables
}
