/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproj;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
//import sql_table.Stores;
//import sql_table.Floor;


/**
 *
 * @author MTC
 */
public class edit_floor1 extends javax.swing.JFrame {

    /**
     * Creates new form Add_store
     */
    
     
    public edit_floor1() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        floorstore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idstore = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addd = new javax.swing.JButton();
        canclee = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtedit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        floorstore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorstoreActionPerformed(evt);
            }
        });
        getContentPane().add(floorstore);
        floorstore.setBounds(160, 190, 192, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Floor Space:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 110, 33);

        idstore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idstoreActionPerformed(evt);
            }
        });
        getContentPane().add(idstore);
        idstore.setBounds(160, 140, 192, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Floor Number:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 20, 110, 33);

        addd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addd.setText("Edit");
        addd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddActionPerformed(evt);
            }
        });
        getContentPane().add(addd);
        addd.setBounds(70, 250, 200, 40);

        canclee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canclee.setText("Cancel");
        canclee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleeActionPerformed(evt);
            }
        });
        getContentPane().add(canclee);
        canclee.setBounds(300, 300, 80, 31);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("     Edit Floor information");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 100, 192, 28);
        getContentPane().add(txtedit);
        txtedit.setBounds(30, 50, 80, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Floor Number:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 140, 130, 33);

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 50, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/downnnload.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 0, 390, 110);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 410, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    
    
    private void floorstoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorstoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorstoreActionPerformed

    private void idstoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idstoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idstoreActionPerformed

    private void adddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddActionPerformed

        
         EntityManagerFactory emf = Persistence.createEntityManagerFactory("GUIprojPU");
        EntityManager em =emf.createEntityManager();
        em.getTransaction().begin();
         String nu;
       
      int num;  
         nu= txtedit.getText();
        num=Integer.parseInt(nu); 
        
          int Idfloor=Integer.parseInt(this.idstore.getText());
           long floorspace= Long.parseLong(this.floorstore.getText());
         
           
           
            
            
 Floor floor = new Floor();
          
          
          
           Query qr1=em.createNamedQuery("Floor.findAll");
      List<Floor> allfloor=qr1.getResultList();
          
          
           boolean t =false;
         
          
          for(Floor ss:allfloor)
          {
          
          if(ss.getFloorId()==Idfloor&&ss.getFloorId()!=num)
          t =true;
         
         }
         
          if(t)
          {
              
           JOptionPane.showMessageDialog(null, " Number  Floor Already exists ");
           
          }
          
      else
          {
      
        
      
             for(Floor ss:allfloor)
          {
          
              
          if(ss.getFloorId()==num)
          {
             ss.setFloorId(Idfloor);
         ss.setFloorSpace(floorspace);
         
         JOptionPane.showMessageDialog(null, "Modified");
           this.setVisible(false);
          }
         
         } 
     
          }
          //end else
          
        em.getTransaction().commit();
          em.close();
           
        
           
        
    }//GEN-LAST:event_adddActionPerformed

    private void cancleeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleeActionPerformed
      
  
        this.setVisible(false);
       
        
        
    }//GEN-LAST:event_cancleeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
          EntityManagerFactory emf = Persistence.createEntityManagerFactory("GUIprojPU");
        EntityManager em =emf.createEntityManager();
        em.getTransaction().begin();
        
  
          String fahs= txtedit.getText();
   
    String nu;
       
      int num;  
   
    if (fahs.equals("")){
        
        
    JOptionPane.showMessageDialog(this, "Enter the Number, please !");
    
    
   return;
    
    }
    
    
    
     nu= txtedit.getText();
        num=Integer.parseInt(nu); 
        Query qr1=em.createNamedQuery("Floor.findAll");
      List<Floor> allfloor=qr1.getResultList();
           Floor floor = new Floor(); 
         
        String s1;
        String s2 ;
      
  
    Stores store=new Stores();
      
boolean xv=false;

             for(Floor ss:allfloor)
                 
                {
            
            if(ss.getFloorId()== num) 
            {
                xv=true;
          
                floor=ss;
                break;
         
            }
                }
       
             
              if(!xv)
          {
             JOptionPane.showMessageDialog(null, " Number Floor Does not exist "); 
          }
           
    
      else
          { 
             
     
        s1=String.valueOf(floor.getFloorId());
        s2 =String.valueOf(floor.getFloorSpace());
          
                                         
         idstore.setText(s1);
         floorstore.setText( s2);
         
       ;
         
                }
              
              
         em.getTransaction().commit();
            em.close();
          
           
           
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_floor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_floor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_floor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_floor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new edit_floor1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addd;
    private javax.swing.JButton canclee;
    private javax.swing.JTextField floorstore;
    private javax.swing.JTextField idstore;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtedit;
    // End of variables declaration//GEN-END:variables
}
