/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproj;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
//import sql_table.Stores;
//import sql_table.Floor;


/**
 *
 * @author MTC
 */
public class edit_EMPLOYEE1 extends javax.swing.JFrame {

    /**
     * Creates new form Add_store
     */
    
     
    public edit_EMPLOYEE1() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        e2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        e1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        e6 = new javax.swing.JTextField();
        e3 = new javax.swing.JTextField();
        addd = new javax.swing.JButton();
        canclee = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtedit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        e4 = new javax.swing.JTextField();
        e5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        e7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ashraf Hamayel\\Desktop\\house-3664320_640.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        getContentPane().add(e2);
        e2.setBounds(210, 180, 192, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("EMPLOYEE ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 170, 150, 33);

        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        getContentPane().add(e1);
        e1.setBounds(210, 140, 192, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("EMPLOYEE  Id :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 20, 160, 33);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("EMPLOYEE  SALARY :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(440, 210, 200, 33);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("EMPLOYEE PHONE:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 180, 176, 27);

        e6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e6ActionPerformed(evt);
            }
        });
        getContentPane().add(e6);
        e6.setBounds(630, 140, 192, 20);

        e3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3ActionPerformed(evt);
            }
        });
        getContentPane().add(e3);
        e3.setBounds(630, 180, 192, 20);

        addd.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        addd.setText("Edit");
        addd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddActionPerformed(evt);
            }
        });
        getContentPane().add(addd);
        addd.setBounds(330, 330, 210, 30);

        canclee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canclee.setText("Cancel");
        canclee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleeActionPerformed(evt);
            }
        });
        getContentPane().add(canclee);
        canclee.setBounds(740, 350, 80, 31);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("    @EMPLOYEE  information");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 380, 230, 20);
        getContentPane().add(txtedit);
        txtedit.setBounds(180, 50, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("EMPLOYEE  NAME :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 130, 190, 33);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 40, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/downnnload.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(630, 0, 225, 90);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("SEX :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 210, 90, 33);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("ADDRESS :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(510, 130, 110, 33);

        e4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e4ActionPerformed(evt);
            }
        });
        getContentPane().add(e4);
        e4.setBounds(630, 220, 192, 20);

        e5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e5ActionPerformed(evt);
            }
        });
        getContentPane().add(e5);
        e5.setBounds(210, 220, 192, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 0));
        jLabel13.setText("FLOOR  NUMBER :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(270, 270, 180, 40);

        e7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e7ActionPerformed(evt);
            }
        });
        getContentPane().add(e7);
        e7.setBounds(440, 280, 192, 20);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/news_img_17737.jpg"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 700, 400);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/employee-silhouette.jpg"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(470, 80, 370, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    
    
    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e2ActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e1ActionPerformed

    private void e6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e6ActionPerformed

    private void e3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e3ActionPerformed

    
    
    private void adddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddActionPerformed

        
        
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("GUIprojPU");
        EntityManager em1 =emf.createEntityManager();
        em1.getTransaction().begin();
            int num;  
            
        String nu= txtedit.getText();
        
        num=Integer.parseInt(nu);
        
        
             Floor f=new Floor();
          String EMPLOYEE_NAME=e1.getText();
           int EMPLOYEE_ID=Integer.parseInt(this.e2.getText());
          long EMPLOYEE_PHONE=Integer.parseInt(this.e3.getText());
           int EMPLOYEE_SALARY=Integer.parseInt(this.e4.getText());
           String EMPLOYEE_SEX=e5.getText();
             String EMPLOYEE_ADDRESS=e6.getText();
          int FLOOR_NUMBER=Integer.parseInt(this.e7.getText());
          
           Query qr1=em1.createNamedQuery("Employee.findAll");
      List<Employee> allEmployee=qr1.getResultList();
           Query qr2=em1.createNamedQuery("Floor.findAll");
          List<Floor> allFloor=qr2.getResultList();
       
           boolean t =false;
          
          
          for(Employee ss:allEmployee)
          {
          
          if(ss.getEmployeeId()==EMPLOYEE_ID&&ss.getEmployeeId()!=num)
          t =true;
         
         }
         
          if(t)
          {
           JOptionPane.showMessageDialog(null, " Id Store Already exists ");
           
           //this.setVisible(false);
          
          }
          else
          {
          
           for(Floor ss:allFloor)
          {
          
          if(ss.getFloorId()==FLOOR_NUMBER)
          t =true;
         
         }
         
          if(!t)
          {
           JOptionPane.showMessageDialog(null, " FLOOR NUMBER Does not exist ");
           
           //this.setVisible(false);
          
          }
          
         
              
          
          
      else
         
          for(Employee ss:allEmployee)
          {
          
          if(ss.getEmployeeId()==EMPLOYEE_ID)
          {
              
         ss.setEmployeeName(EMPLOYEE_NAME);
          ss.setEmployeeId(EMPLOYEE_ID);
              ss.setEmployeePhone(EMPLOYEE_PHONE);
            ss.setEmployeeSalary(EMPLOYEE_SALARY);
             ss.setEmployeeSex(EMPLOYEE_SEX);
             ss.setEmployeeAddress(EMPLOYEE_ADDRESS);
           f.setFloorId(FLOOR_NUMBER);
           ss.setFloorNumber(f);
      
                        
   
        
          
          JOptionPane.showMessageDialog(null, "Modified");
          this.setVisible(false);
          }
          
          }//end else
          
          }
          
        em1.getTransaction().commit();
         em1.close();
         
        
    }//GEN-LAST:event_adddActionPerformed

    private void cancleeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleeActionPerformed
      
  
        this.setVisible(false);
       
        
        
    }//GEN-LAST:event_cancleeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
          EntityManagerFactory emf = Persistence.createEntityManagerFactory("GUIprojPU");
        EntityManager em =emf.createEntityManager();
        em.getTransaction().begin();
        
  
          String fahs= txtedit.getText();
   
    String nu;
       
      int num;  
   
    if (fahs.equals("")){
        
        
    JOptionPane.showMessageDialog(this, "Enter the ID, please !");
    
    
   return;
    
    }
    
    
    
     nu= txtedit.getText();
        num=Integer.parseInt(nu); 
         Query qr1=em.createNamedQuery("Employee.findAll");
      List<Employee> allEmployee=qr1.getResultList();
          
         
        String s1;
        String s2 ;
        String s3 ;
        String s4;  
        String s5 ;
        String s6;
        String s7;  
      
  
  
    Employee Empl=new Employee();
      
boolean xv=false;

             for(Employee ss:allEmployee)
                 
                {
            
            if(ss.getEmployeeId()== num) 
            {
                xv=true;
          
                Empl=ss;
                break;
         
            }
                }
       
             
              if(!xv)
          {
             JOptionPane.showMessageDialog(null, " Id Employee Does not exist "); 
          }
           
    
      else
          { 
             
      s1=String.valueOf(Empl.getEmployeeName());
        s2=String.valueOf(Empl.getEmployeeId());
               s3=String.valueOf(Empl.getEmployeePhone());
            s4=String.valueOf(Empl.getEmployeeSalary());
             s5=String.valueOf(Empl.getEmployeeSex());
             s6=String.valueOf(Empl.getEmployeeAddress());
           
             s7=String.valueOf(Empl.getFloorNumber().getFloorId());
                                         
         e1.setText(s1);
         e2.setText( s2);
         e3.setText( s3 );
         e4.setText( s4);
         e5.setText( s5);
         
         e6.setText(s6 );
           e7.setText(s7 );
            
                }
              
              
         em.getTransaction().commit();
            em.close();
          
           
           
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void e4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e4ActionPerformed

    private void e5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e5ActionPerformed

    private void e7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_EMPLOYEE1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_EMPLOYEE1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_EMPLOYEE1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_EMPLOYEE1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new edit_EMPLOYEE1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addd;
    private javax.swing.JButton canclee;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e3;
    private javax.swing.JTextField e4;
    private javax.swing.JTextField e5;
    private javax.swing.JTextField e6;
    private javax.swing.JTextField e7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtedit;
    // End of variables declaration//GEN-END:variables
}
