/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproj;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
//import sql_table.Stores;
//import sql_table.Floor;


/**
 *
 * @author MTC
 */
public class edit_tant1 extends javax.swing.JFrame {

    /**
     * Creates new form Add_store
     */
    
     
    public edit_tant1() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ad2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ad1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ad6 = new javax.swing.JTextField();
        ad3 = new javax.swing.JTextField();
        addd = new javax.swing.JButton();
        canclee = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtedit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ad4 = new javax.swing.JTextField();
        ad5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ad7 = new javax.swing.JTextField();
        ad8 = new javax.swing.JTextField();
        ad9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ashraf Hamayel\\Desktop\\house-3664320_640.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad2ActionPerformed(evt);
            }
        });
        getContentPane().add(ad2);
        ad2.setBounds(210, 180, 192, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TENANT ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 170, 150, 33);

        ad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad1ActionPerformed(evt);
            }
        });
        getContentPane().add(ad1);
        ad1.setBounds(210, 140, 192, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Store  Id :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 10, 120, 33);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID STORE:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 250, 130, 33);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TENANT PHONE:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 220, 176, 27);

        ad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad6ActionPerformed(evt);
            }
        });
        getContentPane().add(ad6);
        ad6.setBounds(630, 140, 192, 20);

        ad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad3ActionPerformed(evt);
            }
        });
        getContentPane().add(ad3);
        ad3.setBounds(210, 220, 192, 20);

        addd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addd.setText("Edit");
        addd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddActionPerformed(evt);
            }
        });
        getContentPane().add(addd);
        addd.setBounds(350, 340, 210, 30);

        canclee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canclee.setText("Cancel");
        canclee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleeActionPerformed(evt);
            }
        });
        getContentPane().add(canclee);
        canclee.setBounds(710, 380, 80, 31);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("    @TENANT  information");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 400, 230, 28);
        getContentPane().add(txtedit);
        txtedit.setBounds(290, 50, 80, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TENANT  NAME :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 130, 160, 33);

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 40, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/downnnload.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(620, 0, 225, 110);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SEX :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 300, 90, 33);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ADDRESS :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(510, 130, 110, 33);

        ad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad4ActionPerformed(evt);
            }
        });
        getContentPane().add(ad4);
        ad4.setBounds(210, 260, 192, 20);

        ad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad5ActionPerformed(evt);
            }
        });
        getContentPane().add(ad5);
        ad5.setBounds(210, 310, 192, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("STORE TYPE :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(490, 180, 140, 33);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CONTRACT START DATE:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(410, 220, 230, 33);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CONTRACT END DATE:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(420, 270, 210, 33);

        ad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad7ActionPerformed(evt);
            }
        });
        getContentPane().add(ad7);
        ad7.setBounds(630, 190, 192, 20);

        ad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad8ActionPerformed(evt);
            }
        });
        getContentPane().add(ad8);
        ad8.setBounds(630, 230, 192, 20);

        ad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad9ActionPerformed(evt);
            }
        });
        getContentPane().add(ad9);
        ad9.setBounds(630, 280, 192, 20);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/123873925_425937291754981_2960794812061363717_n.jpg"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 860, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    
    
    private void ad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad2ActionPerformed

    private void ad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad1ActionPerformed

    private void ad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad6ActionPerformed

    private void ad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad3ActionPerformed

    
    
    private void adddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddActionPerformed

        
        
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("GUIprojPU");
        EntityManager em1 =emf.createEntityManager();
        em1.getTransaction().begin();
            int num;  
            
        String nu= txtedit.getText();
        
        num=Integer.parseInt(nu);
        
        
        
         String name=ad1.getText();
           int tid=Integer.parseInt(this.ad2.getText());
          long tphon=Integer.parseInt(this.ad3.getText());
           int tidstore=Integer.parseInt(this.ad4.getText());
          String taddres=ad6.getText();
           String tsex=ad5.getText();
           String storetype=ad7.getText();
            String tsdate=ad8.getText();
             String tedate=ad9.getText();
          
           Query qr1=em1.createNamedQuery("TenantOwner.findAll");
      List<TenantOwner> alltnt=qr1.getResultList();
          
       
           boolean t =false;
          
          
          for(TenantOwner ss:alltnt)
          {
          
          if(ss.getIdStore()==tidstore&&ss.getIdStore()!=num)
          t =true;
         
         }
         
          if(t)
          {
           JOptionPane.showMessageDialog(null, " Id Store Already exists ");
           
           //this.setVisible(false);
          
          }
      else
         
          for(TenantOwner ss:alltnt)
          {
          
          if(ss.getIdStore()==tidstore)
          {
              
        ss.setTenantOwnerName(name);
        
          ss.setTenantOwnerId(tid);
          
            ss.setTenantOwnerPhone(tphon);
            
           
              ss.setIdStore(tidstore);
              
                ss.setAddress(taddres);
                
                  ss.setSex(tsex);
                  
                    ss.setStoreType(storetype);
                    
                      ss.setContractStartDate(tsdate);
                      
                        ss.setContractEndDate(tedate);
          
          JOptionPane.showMessageDialog(null, "Modified");
          this.setVisible(false);
          }
          
          }//end else
          
          
          
        em1.getTransaction().commit();
         em1.close();
         
        
    }//GEN-LAST:event_adddActionPerformed

    private void cancleeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleeActionPerformed
      
  
        this.setVisible(false);
       
        
        
    }//GEN-LAST:event_cancleeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
          EntityManagerFactory emf = Persistence.createEntityManagerFactory("GUIprojPU");
        EntityManager em =emf.createEntityManager();
        em.getTransaction().begin();
        
  
          String fahs= txtedit.getText();
   
    String nu;
       
      int num;  
   
    if (fahs.equals("")){
        
        
    JOptionPane.showMessageDialog(this, "Enter the ID, please !");
    
    
   return;
    
    }
    
    
    
     nu= txtedit.getText();
        num=Integer.parseInt(nu); 
         Query qr1=em.createNamedQuery("TenantOwner.findAll");
      List<TenantOwner> alltnt=qr1.getResultList();
          
         
        String s1;
        String s2 ;
        String s3 ;
        String s4;  
        String s5 ;
        String s6;
        String s7;  
        String s8 ;
        String s9;  
  
  
    TenantOwner tnt=new TenantOwner();
      
boolean xv=false;

             for(TenantOwner ss:alltnt)
                 
                {
            
            if(ss.getIdStore()== num) 
            {
                xv=true;
          
                tnt=ss;
                break;
         
            }
                }
       
             
              if(!xv)
          {
             JOptionPane.showMessageDialog(null, " Id Store Does not exist "); 
          }
           
    
      else
          { 
             
     
        s1=String.valueOf(tnt.getTenantOwnerName());
        s2=String.valueOf(tnt.getTenantOwnerId());
         s3=String.valueOf(tnt.getTenantOwnerPhone());
        
          s4=String.valueOf(tnt.getIdStore());
           s5=String.valueOf(tnt.getAddress());
          
            s6=String.valueOf(tnt.getSex());
             s7=String.valueOf(tnt.getStoreType());
              s8=String.valueOf(tnt.getContractStartDate());
               s9=String.valueOf(tnt.getContractEndDate());
                                         
         ad1.setText(s1);
         ad2.setText( s2);
         ad3.setText( s3 );
         ad4.setText( s4);
         ad5.setText( s6);
         
         ad6.setText(s5 );
           ad7.setText(s7 );
             ad8.setText(s8 );
               ad9.setText(s9 );
         
                }
              
              
         em.getTransaction().commit();
            em.close();
          
           
           
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad4ActionPerformed

    private void ad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad5ActionPerformed

    private void ad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad7ActionPerformed

    private void ad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad8ActionPerformed

    private void ad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_tant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_tant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_tant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_tant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new edit_tant1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad1;
    private javax.swing.JTextField ad2;
    private javax.swing.JTextField ad3;
    private javax.swing.JTextField ad4;
    private javax.swing.JTextField ad5;
    private javax.swing.JTextField ad6;
    private javax.swing.JTextField ad7;
    private javax.swing.JTextField ad8;
    private javax.swing.JTextField ad9;
    private javax.swing.JButton addd;
    private javax.swing.JButton canclee;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtedit;
    // End of variables declaration//GEN-END:variables
}
