/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproj;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
//import sql_table.Stores;
//import sql_table.Floor;


/**
 *
 * @author MTC
 */
public class edit_store extends javax.swing.JFrame {

    /**
     * Creates new form Add_store
     */
    
     
    public edit_store() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        floorstore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idstore = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        storeowner = new javax.swing.JTextField();
        storeyear = new javax.swing.JTextField();
        addd = new javax.swing.JButton();
        canclee = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtedit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        floorstore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorstoreActionPerformed(evt);
            }
        });
        getContentPane().add(floorstore);
        floorstore.setBounds(210, 160, 192, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("store Floor:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 160, 90, 33);

        idstore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idstoreActionPerformed(evt);
            }
        });
        getContentPane().add(idstore);
        idstore.setBounds(210, 120, 192, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("store id:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 20, 88, 33);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("STORE PRICE TO OWNER:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 250, 185, 33);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("STORE PRICE PER YEAR:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 210, 176, 27);

        storeowner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeownerActionPerformed(evt);
            }
        });
        getContentPane().add(storeowner);
        storeowner.setBounds(210, 260, 192, 20);

        storeyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeyearActionPerformed(evt);
            }
        });
        getContentPane().add(storeyear);
        storeyear.setBounds(210, 210, 192, 20);

        addd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addd.setText("Edit");
        addd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddActionPerformed(evt);
            }
        });
        getContentPane().add(addd);
        addd.setBounds(100, 300, 171, 31);

        canclee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canclee.setText("Cancel");
        canclee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleeActionPerformed(evt);
            }
        });
        getContentPane().add(canclee);
        canclee.setBounds(320, 320, 80, 31);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("     Edit store information");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 90, 192, 28);
        getContentPane().add(txtedit);
        txtedit.setBounds(50, 50, 80, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("store id:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 120, 88, 33);

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 43, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/downnnload.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, -20, 210, 130);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/item_XL_32406519_141044529.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 410, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    
    
    private void floorstoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorstoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorstoreActionPerformed

    private void idstoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idstoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idstoreActionPerformed

    private void storeownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeownerActionPerformed

    private void storeyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeyearActionPerformed

    private void adddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddActionPerformed

        
         EntityManagerFactory emf = Persistence.createEntityManagerFactory("GUIprojPU");
        EntityManager em =emf.createEntityManager();
        em.getTransaction().begin();
         String nu;
       
      int num;  
         nu= txtedit.getText();
        num=Integer.parseInt(nu); 
        
           int IdStore=Integer.parseInt(idstore.getText());
           int floorStore=Integer.parseInt(floorstore.getText());
          int yearStore=Integer.parseInt(storeyear.getText());
           int ownerStore=Integer.parseInt(storeowner.getText());
           
           
            
            
 Floor f = new Floor();
          
          
          
           Query qr1=em.createNamedQuery("Stores.findAll");
      List<Stores> allstore=qr1.getResultList();
          
          Query qr2=em.createNamedQuery("Floor.findAll");
          List<Floor> allfloor=qr2.getResultList();
          
           boolean t =false;
         
          
          for(Stores ss:allstore)
          {
          
          if(ss.getIdStore()==IdStore&&ss.getIdStore()!=num)
          t =true;
         
         }
         
          if(t)
          {
              
           JOptionPane.showMessageDialog(null, " Id Store Already exists ");
           
          }
          
      else
          {
      
        
          for (Floor ff:allfloor)
          {
              
         if(ff.getFloorId()==floorStore)
          t =true;
         
          }
          
           if(!t)
          {
           JOptionPane.showMessageDialog(null, " Id Floor Does not exist ");
           
         
          
          }
      else
          {
         
            
             for(Stores ss:allstore)
          {
          
              
          if(ss.getIdStore()==IdStore)
          {
              ss.setIdStore(IdStore);
         f.setFloorId(floorStore);
        ss.setStoreFloor(f);
        ss.setStorePricePerYear(yearStore);
        ss.setStorePriceToOwn(ownerStore); 
         JOptionPane.showMessageDialog(null, "Modified");
           this.setVisible(false);
          }
         
         } 
     
          }
          }//end else
          
        em.getTransaction().commit();
          em.close();
           
        
           
        
    }//GEN-LAST:event_adddActionPerformed

    private void cancleeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleeActionPerformed
      
  
        this.setVisible(false);
       
        
        
    }//GEN-LAST:event_cancleeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
          EntityManagerFactory emf = Persistence.createEntityManagerFactory("GUIprojPU");
        EntityManager em =emf.createEntityManager();
        em.getTransaction().begin();
        
  
          String fahs= txtedit.getText();
   
    String nu;
       
      int num;  
   
    if (fahs.equals("")){
        
        
    JOptionPane.showMessageDialog(this, "Enter the ID, please !");
    
    
   return;
    
    }
    
    
    
     nu= txtedit.getText();
        num=Integer.parseInt(nu); 
         Query qr1=em.createNamedQuery("Stores.findAll");
      List<Stores> allstore=qr1.getResultList();
          
         
        String s1;
        String s2 ;
        String s3 ;
        String s4;    
  
    Stores store=new Stores();
      
boolean xv=false;

             for(Stores ss:allstore)
                 
                {
            
            if(ss.getIdStore()== num) 
            {
                xv=true;
          
                store=ss;
                break;
         
            }
                }
       
             
              if(!xv)
          {
             JOptionPane.showMessageDialog(null, " Id store Does not exist "); 
          }
           
    
      else
          { 
             
     
        s1=String.valueOf(store.getIdStore());
        s2 =String.valueOf(store.getStoreFloor().getFloorId());
         s3 =String.valueOf(store.getStorePricePerYear());
         s4 =String.valueOf(store.getStorePriceToOwn());          
                                         
         idstore.setText(s1);
         floorstore.setText( s2);
         storeyear.setText( s3 );
         storeowner.setText(s4 );
         
                }
              
              
         em.getTransaction().commit();
            em.close();
          
           
           
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new edit_store().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addd;
    private javax.swing.JButton canclee;
    private javax.swing.JTextField floorstore;
    private javax.swing.JTextField idstore;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField storeowner;
    private javax.swing.JTextField storeyear;
    private javax.swing.JTextField txtedit;
    // End of variables declaration//GEN-END:variables
}
