/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproj;

/**
 *
 * @author MTC
 */
public class Home_screen extends javax.swing.JFrame {

    
    public Home_screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        st = new javax.swing.JToggleButton();
        tenants = new javax.swing.JButton();
        employee = new javax.swing.JButton();
        ADVER = new javax.swing.JButton();
        floorr = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 30, 24));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sakkal Majalla", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 200, 40));

        st.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        st.setForeground(new java.awt.Color(217, 30, 24));
        st.setText("Store's");
        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });
        jPanel1.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 40));

        tenants.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tenants.setForeground(new java.awt.Color(217, 30, 24));
        tenants.setText("Tenants");
        tenants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantsActionPerformed(evt);
            }
        });
        jPanel1.add(tenants, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 280, 40));

        employee.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        employee.setForeground(new java.awt.Color(217, 30, 24));
        employee.setText("Employee");
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });
        jPanel1.add(employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 280, 40));

        ADVER.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ADVER.setForeground(new java.awt.Color(217, 30, 24));
        ADVER.setText("Advertising");
        ADVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADVERActionPerformed(evt);
            }
        });
        jPanel1.add(ADVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 280, 40));

        floorr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        floorr.setForeground(new java.awt.Color(217, 30, 24));
        floorr.setText("Floor's");
        floorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorrActionPerformed(evt);
            }
        });
        jPanel1.add(floorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 280, 40));

        close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        close.setForeground(new java.awt.Color(217, 30, 24));
        close.setText("Close  :(");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 280, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/sososss.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 290, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 491));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(217, 30, 24));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Blackadder ITC", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("welcome abo hamza  ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 0, 480, 61));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/sososss.jpg"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 690, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproj/zzzz.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 250, 270));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Home");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 680, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed
       StoreGUI op5 = new StoreGUI();
         
        this.setVisible(false);
        op5.setVisible(true);
    }//GEN-LAST:event_stActionPerformed

    private void tenantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantsActionPerformed
       
        TENANTSGUI1 tnt=new TENANTSGUI1();
         this.setVisible(false);
        tnt.setVisible(true);
        
    }//GEN-LAST:event_tenantsActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
       System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void floorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorrActionPerformed
       FloorGUI1 flo=new FloorGUI1();
        this.setVisible(false);
        flo.setVisible(true);
    }//GEN-LAST:event_floorrActionPerformed

    private void ADVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADVERActionPerformed
        ADVERTISINGGUI1 adv=new ADVERTISINGGUI1();
         this.setVisible(false);
        adv.setVisible(true);
    }//GEN-LAST:event_ADVERActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
       EMPLOYEEGUI1 EMPLOYEE=new EMPLOYEEGUI1();
         this.setVisible(false);
        EMPLOYEE.setVisible(true);
        
        
        
    }//GEN-LAST:event_employeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADVER;
    private javax.swing.JButton close;
    private javax.swing.JButton employee;
    private javax.swing.JButton floorr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton st;
    private javax.swing.JButton tenants;
    // End of variables declaration//GEN-END:variables
}
